pokemon/users/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from pokemon.extensions import db, bcrypt
from pokemon.models import User
from flask_login import login_user, logout_user, current_user, login_required

users_bp = Blueprint('users', __name__, template_folder='templates')

@users_bp.route('/')
@login_required
def index():
  return render_template('users/index.html', title='User Page')

@users_bp.route('/register', methods=['GET', 'POST'])
def register():
  if request.method == 'POST':
    username = request.form.get('username')
    email = request.form.get('email')
    password = request.form.get('password')
    confirm_password = request.form.get('confirm_password')

    query = db.select(User).where(User.username==username)
    user = db.session.scalar(query)
    if user:
      flash('Username is already exists!', 'warning')
      return redirect(url_for('users.register'))
    else:
      query = db.select(User).where(User.email==email)
      user = db.session.scalar(query)
      if user:
        flash('Email is already exists!', 'warning')
        return redirect(url_for('users.register'))
      else:
        if password == confirm_password:
          pwd_hash = bcrypt.generate_password_hash(password=password).decode('utf-8')
          user = User(username=username, email=email, password=pwd_hash)
          db.session.add(user)
          db.session.commit()
          flash('Register successful!', 'success')
          return redirect(url_for('users.login'))
        else:
          flash('Your password not match!', 'warning')
          return redirect(url_for('users.register'))
  return render_template('users/register.html', title='Register Page')

@users_bp.route('/login', methods=['GET', 'POST'])
def login():
  if request.method == 'POST':
    username = request.form.get('username')
    password = request.form.get('password')

    query = db.select(User).where(User.username==username)
    user = db.session.scalar(query)
    if user:
      if bcrypt.check_password_hash(user.password, password):
        login_user(user)
        flash('Login successful!', 'success')
        return redirect(url_for('users.index'))
      else:
        flash('Password is not match!', 'warning')
        return redirect(url_for('users.login'))
    else:
      flash('Username is not exists!', 'warning')
      return redirect(url_for('users.login'))
  return render_template('users/login.html', title='Login Page')

@users_bp.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
  logout_user()
  return redirect(url_for('core.index'))

@users_bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
  user = current_user
  if request.method == 'POST':
    firstname = request.form.get('firstname')
    lastname = request.form.get('lastname')
    if len(firstname)>0 and len(lastname)>0:
      user.firstname = firstname
      user.lastname = lastname
      db.session.add(user)
      db.session.commit()
      flash('Update profile successful!', 'success')
      return redirect(url_for('users.profile'))
    
  return render_template('users/profile.html', 
                         title='Profile Page',
                         user=user)

pokemon/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap" rel="stylesheet">
  <link rel="shortcut icon" href="{{url_for('static', filename='img/favicon.ico')}}" type="image/x-icon">
  <link rel="icon" href="{{url_for('static', filename='img/favicon.ico')}}" type="image/x-icon">
  <script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.8/dist/htmx.min.js" integrity="sha384-/TgkGk7p307TH7EXJDuUlgG3Ce1UVolAOFopFekQkkXihi5u/6OCvVKyz1W+idaz" crossorigin="anonymous"></script>
  <title>Pokemon Go - {% block title %}{% endblock %}
  </title>
  <style>
    * {
      font-family: 'Nunito', sans-serif;
      .card-pokemon {
        transition: transform .5s;
      }
      .card-pokemon:hover {
        transform: scale(1.05);
      }
    }
  </style>
</head>
<body>
  {% include "navbar.html" %}
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      
      {% for category, message in messages %}
        <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
          <strong>{{message}}</strong>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endfor %}
      
    {% endif %}
  {% endwith %}
  {% block content %}{% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</body>
</html>

pokemon/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    {% if current_user.is_authenticated %}
        <a class="navbar-brand" href="#">Pokemon Go</a>
    {% else %}
        <a class="navbar-brand" href="{{url_for('core.index')}}">Pokemon Go</a>
    {% endif %}
    
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      {% if current_user.is_authenticated %}
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{url_for('users.index')}}">Home</a>
          </li>
          <li class="nav-item">
            <a href="{{url_for('pokemon.index')}}" class="nav-link">Pokemons</a>
          </li>
        </ul>
      {% else %}
        <ul class="navbar-nav me-auto">
          
          <li class="nav-item">
            
          </li>
        </ul>
      {% endif %}
      
      
      
      <ul class="navbar-nav">
        {% if current_user.is_authenticated %}
            
          <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="{{ url_for('static', filename='img/' + current_user.avatar) }}" alt="" width="25" height="25" class="rounded-circle">
        Welcome, {{ current_user.username }}
    </a>
    <ul class="dropdown-menu dropdown-menu-end">
        <li>
            <a class="dropdown-item" href="{{ url_for('users.profile') }}">
                <i class="bi bi-person-square"></i> Profile
            </a>
        </li>
        <li>
            <a class="dropdown-item" href="{{ url_for('core.change_password') }}">
                <i class="bi bi-key-fill"></i> Change Password
            </a>
        </li>
        <li><hr class="dropdown-divider"></li>
        <li>
            <a class="dropdown-item" href="{{ url_for('users.logout') }}">
                <i class="bi bi-box-arrow-left"></i> Logout
            </a>
        </li>
    </ul>
</li>
              </ul>
            </li>
        {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('users.login')}}">Login</a>
            </li>
        
        
        {% endif %}
      </ul>
      
    </div>
  </div>
</nav>